# SPDX-FileCopyrightText: 2025-2026 Damian Fajfer <damian@fajfer.org>
#
# SPDX-License-Identifier: EUPL-1.2

"""Metrics package for Chronowarden."""

from chronowarden.metrics.prometheus import (
    API_REQUEST_DURATION_SECONDS,
    API_REQUESTS_TOTAL,
    INTEGRATION_HEALTH,
    NOTIFICATIONS_SENT_TOTAL,
    SECRETS_EXPIRED,
    SECRETS_EXPIRING_SOON,
    SECRETS_TOTAL,
    VAULT_CONNECTIONS_TOTAL,
    VAULT_OPERATION_DURATION_SECONDS,
    VAULT_OPERATIONS_TOTAL,
)

__all__ = [
    "API_REQUEST_DURATION_SECONDS",
    "API_REQUESTS_TOTAL",
    "INTEGRATION_HEALTH",
    "NOTIFICATIONS_SENT_TOTAL",
    "SECRETS_EXPIRED",
    "SECRETS_EXPIRING_SOON",
    "SECRETS_TOTAL",
    "VAULT_CONNECTIONS_TOTAL",
    "VAULT_OPERATION_DURATION_SECONDS",
    "VAULT_OPERATIONS_TOTAL",
]
