# SPDX-FileCopyrightText: 2026 Damian Fajfer <damian@fajfer.org>
#
# SPDX-License-Identifier: EUPL-1.2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chronowarden-data
  namespace: chronowarden
  labels:
    app.kubernetes.io/name: chronowarden
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
